lib/mango_web/router.ex
defmodule MangoWeb.Router do
  use MangoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MangoWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/categories/:name", CategoryController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", MangoWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: MangoWeb.Telemetry
    end
  end
end

lib/mango/application.ex
defmodule Mango.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      Mango.Repo,
      # Start the Telemetry supervisor
      MangoWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Mango.PubSub},
      # Start the Endpoint (http/https)
      MangoWeb.Endpoint
      # Start a worker by calling: Mango.Worker.start_link(arg)
      # {Mango.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Mango.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    MangoWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/mango/catalog/catalog.ex
defmodule Mango.Catalog do
  alias Mango.Catalog.Product
  alias Mango.Repo

  def list_products do
    Product
    |> Repo.all()
  end

  def list_seasonal_products do
    list_products()
    |> Enum.filter(fn product -> product.is_seasonal end)
  end

  def get_category_products(product_category) do
    list_products()
    |> Enum.filter(fn product -> product.category == product_category end)
  end
end

lib/mango/catalog/product.ex
defmodule Mango.Catalog.Product do
  use Ecto.Schema

  schema "products" do
    field :image, :string
    field :is_seasonal, :boolean, default: false
    field :name, :string
    field :price, :decimal
    field :sku, :string
    field :category, :string
    field :pack_size, :string

    timestamps()
  end
end

lib/mango/repo.ex
defmodule Mango.Repo do
  use Ecto.Repo,
    otp_app: :mango,
    adapter: Ecto.Adapters.Postgres
end

lib/mango_web/controllers/category_controller.ex
defmodule MangoWeb.CategoryController do
  use MangoWeb, :controller

  alias Mango.Catalog

  def show(conn, %{"name" => name}) do
    products = Catalog.get_category_products(name)

    conn
    |> assign(:products, products)
    |> assign(:name, name)
    |> render("show.html")
  end
end

lib/mango_web/controllers/page_controller.ex
defmodule MangoWeb.PageController do
  use MangoWeb, :controller

  alias Mango.Catalog

  def index(conn, _params) do
    seasonal_products = Catalog.list_seasonal_products()

    render(conn, "index.html", seasonal_products: seasonal_products)
  end
end

lib/mango_web/views/category_view.ex
defmodule MangoWeb.CategoryView do
  use MangoWeb, :view

  def title_case(name) do
    name
    |> String.downcase()
    |> String.capitalize()
  end
end

lib/mango_web/views/error_view.ex
defmodule MangoWeb.ErrorView do
  use MangoWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/mango_web/views/layout_view.ex
defmodule MangoWeb.LayoutView do
  use MangoWeb, :view
end

lib/mango_web/views/page_view.ex
defmodule MangoWeb.PageView do
  use MangoWeb, :view
end

lib/mango_web/views/product_view.ex
defmodule MangoWeb.ProductView do
  use MangoWeb, :view
end

lib/mango_web/templates/category/show.html.eex
<h1 class="page-title"><%= title_case @name %></h1>
<div class="product-container">
    <%= for product <- @products do %>
    <%= render MangoWeb.ProductView, "product_card.html", product: product %>
    <% end %>
</div>

lib/mango_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Mango · Phoenix Framework</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
    integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>" />
  <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
</head>

<body>
  <%= render "app_nav.html", conn: @conn %>
  <main role="main" class="container">
    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    <%= @inner_content %>
  </main>
</body>

</html>

lib/mango_web/templates/layout/app_nav.html.eex
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">
        <div class="logo-link">
            <img src="/images/logo.png" class="small" />
            <p>Sabji Wala</p>
        </div>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item px-2">
                <%= link "Fruits", to: Routes.category_path(@conn, :show, "fruits") %>
            </li>

            <li class="nav-item px-2">
                <%= link "Vegetables", to: Routes.category_path(@conn, :show, "vegetables") %>
            </li>
        </ul>
    </div>
</nav>

lib/mango_web/templates/page/index.html.eex
<h1 class="page-title">Seasonal Products</h1>
<div class="product-container">
    <%= for product <- @seasonal_products do  %>
    <div>
        <%= render MangoWeb.ProductView, "product_card.html", product: product %>
    </div>
    <% end %>
</div>

lib/mango_web/templates/product/product_card.html.eex
<div class="product">
    <section class="top">
        <div class="product-name"><%= @product.name %></div>
        <span class="product-size"><%= @product.pack_size %></span>
    </section>
    <section class="image">
        <img src="<%= @product.image %>" />
    </section>
    <section class="bottom">
        <section class="product-price">&#8377;<%= @product.price %></section>
        <section class="quantity">
            <button class="decrease">-</button>
            <span type="text" class="count">0</span>
            <button class="increase">+</button>
        </section>
    </section>
</div>